const Index = {
    PRO_BARCODE_UNIQUE_INDEX: 'PRO_BARCODE_UNIQUE_INDEX',
    ORD_CODE_UNIQUE_INDEX: 'ORD_CODE_UNIQUE_INDEX',
    USR_NIU_UNIQUE_INDEX: 'USR_NIU_UNIQUE_INDEX',
    USR_EMAIL_UNIQUE_INDEX: 'USR_EMAIL_UNIQUE_INDEX',
    CLI_NIU_UNIQUE_INDEX: 'CLI_NIU_UNIQUE_INDEX',
    CLI_EMAIL_UNIQUE_INDEX: 'CLI_EMAIL_UNIQUE_INDEX',
}

module.exports = Index;