-- CreateTable
CREATE TABLE `products` (
    `PRO_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PRO_CODE` VARCHAR(191) NOT NULL,
    `PRO_TITLE` VARCHAR(255) NOT NULL,
    `PRO_DESCRIPTION` LONGTEXT NOT NULL,
    `PRO_CATEGORY` VARCHAR(50) NOT NULL,
    `PRO_SUBCAT` VARCHAR(50) NULL,
    `PRO_BRAND` VARCHAR(50) NOT NULL,
    `PRO_MODEL` VARCHAR(50) NOT NULL,
    `PRO_STOCK` INTEGER NOT NULL,
    `PRO_PROPER` JSON NOT NULL,
    `PRO_REG_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `PRO_UPD_DATE` DATETIME(3) NULL,

    UNIQUE INDEX `PRO_BARCODE_UNIQUE_INDEX`(`PRO_CODE`),
    PRIMARY KEY (`PRO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `orders` (
    `ORD_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ORD_CODE` VARCHAR(191) NOT NULL,
    `ORD_SELLER` VARCHAR(10) NOT NULL,
    `ORD_CLIENT` VARCHAR(10) NOT NULL,
    `ORD_TOTAL` DOUBLE NOT NULL,
    `ORD_DISCOUNT` DOUBLE NOT NULL DEFAULT 0.00,
    `ORD_SHIP_ADDR` INTEGER NOT NULL,
    `ORD_STATUS` ENUM('PENDING', 'CONFIRMED', 'DISPACHED', 'DELIVERED') NOT NULL DEFAULT 'PENDING',
    `ORD_REG_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ORD_UPD_DATE` DATETIME NULL,

    UNIQUE INDEX `ORD_CODE_UNIQUE_INDEX`(`ORD_CODE`),
    PRIMARY KEY (`ORD_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `order_items` (
    `PRO_ID` INTEGER NOT NULL,
    `ORD_ID` INTEGER NOT NULL,
    `ORD_ITEM_DISCOUNT` DOUBLE NOT NULL DEFAULT 0.00,

    PRIMARY KEY (`ORD_ID`, `PRO_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `users` (
    `USR_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USR_LOGIN` VARCHAR(10) NOT NULL,
    `USR_FNAME` VARCHAR(50) NOT NULL,
    `USR_LNAME` VARCHAR(50) NOT NULL,
    `USR_BIRTHDAY` DATE NOT NULL,
    `USR_EMAIL` VARCHAR(100) NOT NULL,
    `USR_PASSWORD` VARCHAR(170) NOT NULL,
    `USR_ROLE` ENUM('SALESMAN', 'ADMIN') NOT NULL DEFAULT 'SALESMAN',
    `USR_STATUS` BOOLEAN NOT NULL DEFAULT false,
    `USR_INIT_DAY` DATETIME NULL,
    `USR_REG_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `USR_UPD_DATE` DATETIME(3) NULL,

    UNIQUE INDEX `USR_NIU_UNIQUE_INDEX`(`USR_LOGIN`),
    UNIQUE INDEX `USR_EMAIL_UNIQUE_INDEX`(`USR_EMAIL`),
    PRIMARY KEY (`USR_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `clients` (
    `CLI_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CLI_NIU` VARCHAR(10) NOT NULL,
    `CLI_NAME` VARCHAR(100) NOT NULL,
    `CLI_BIRTHDAY` DATE NULL,
    `CLI_EMAIL` VARCHAR(100) NULL,
    `CLI_REG_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CLI_UPD_DATE` DATETIME(3) NULL,

    UNIQUE INDEX `CLI_NIU_UNIQUE_INDEX`(`CLI_NIU`),
    UNIQUE INDEX `CLI_EMAIL_UNIQUE_INDEX`(`CLI_EMAIL`),
    PRIMARY KEY (`CLI_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `addresses` (
    `ADR_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ADR_DESC` VARCHAR(100) NOT NULL,
    `ADR_ZIP` VARCHAR(10) NULL,
    `ADR_CITY` VARCHAR(50) NOT NULL,
    `ADR_STATE` VARCHAR(50) NOT NULL,
    `ADR_DETAIL` VARCHAR(255) NULL,
    `ADR_TYPE` ENUM('RESIDENTIAL', 'COMMERCIAL') NOT NULL DEFAULT 'RESIDENTIAL',
    `ADR_USR_NIU` VARCHAR(10) NULL,
    `ADR_CLI_NIU` VARCHAR(10) NULL,
    `ADR_PRIMARY` BOOLEAN NOT NULL DEFAULT false,
    `ADR_REG_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ADR_UPD_DATE` DATETIME NULL,

    PRIMARY KEY (`ADR_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `telephones` (
    `TEL_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `TEL_NUM` VARCHAR(8) NOT NULL,
    `TEL_TYPE` ENUM('RESIDENTIAL', 'COMMERCIAL') NOT NULL DEFAULT 'RESIDENTIAL',
    `TEL_USR_NIU` VARCHAR(10) NULL,
    `TEL_CLI_NIU` VARCHAR(10) NULL,
    `TEL_REG_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `TEL_UPD_DATE` DATETIME NULL,

    PRIMARY KEY (`TEL_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `orders` ADD CONSTRAINT `USER_ORDER_FK` FOREIGN KEY (`ORD_SELLER`) REFERENCES `users`(`USR_LOGIN`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `orders` ADD CONSTRAINT `CLIENT_ORDER_FK` FOREIGN KEY (`ORD_CLIENT`) REFERENCES `clients`(`CLI_NIU`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `orders` ADD CONSTRAINT `ADDRESS_ORDER_FK` FOREIGN KEY (`ORD_SHIP_ADDR`) REFERENCES `addresses`(`ADR_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `order_items` ADD CONSTRAINT `ODER_ITEM_PRODUCT_FK` FOREIGN KEY (`PRO_ID`) REFERENCES `products`(`PRO_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `order_items` ADD CONSTRAINT `ORDER_ITEM_ITEM_FK` FOREIGN KEY (`ORD_ID`) REFERENCES `orders`(`ORD_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `addresses` ADD CONSTRAINT `USER_ADDRESSES_FK` FOREIGN KEY (`ADR_USR_NIU`) REFERENCES `users`(`USR_LOGIN`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `addresses` ADD CONSTRAINT `CLIENT_ADDRESSES_FK` FOREIGN KEY (`ADR_CLI_NIU`) REFERENCES `clients`(`CLI_NIU`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `telephones` ADD CONSTRAINT `USER_TELEPHONES_FK` FOREIGN KEY (`TEL_USR_NIU`) REFERENCES `users`(`USR_LOGIN`) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `telephones` ADD CONSTRAINT `CLIENT_TELEPHONES_FK` FOREIGN KEY (`TEL_CLI_NIU`) REFERENCES `clients`(`CLI_NIU`) ON DELETE NO ACTION ON UPDATE CASCADE;
