-- AlterTable
ALTER TABLE `addresses` MODIFY `ADR_ZIP` VARCHAR(10) NULL,
    MODIFY `ADR_DETAIL` VARCHAR(255) NULL;

-- AlterTable
ALTER TABLE `users` ADD COLUMN `USR_INIT_DAY` DATETIME NULL,
    MODIFY `USR_PASSWORD` VARCHAR(170) NOT NULL;
